version: "3.1"

services:
  mongo:
    image: mongo:6.0.2
    container_name: backend-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
  mongo-test:
    image: mongo:6.0.2
    container_name: backend-db-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27018:27017"